version: '3.8'
services:
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tmbcontrol
      POSTGRES_PASSWORD: <escribe la contraseña de la base de datos>
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    logging:
      driver: json-file
      options:
      max-size: "10m"
      max-file: "5"
      
  mailhog:
    image: mailhog/mailhog
    restart: always
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  backend-api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: backend-api
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=tmbcontrol;Username=postgres;Password=<escribe la contraseña de la base de datos>
      - Jwt__Key=<escribe la clave secreta jJWT>
      - ApiKeys__0__name=<escribe un nombre descriptivo para el ApiKey>
      - ApiKeys__0__key=<escribe el ApiKey>
      - Cors__AllowedOrigins__0=<escribe la URL que permite el acceso el backend>
      - AdminUser__Name=<escribe el nombre del administrador>
      - AdminUser__Email=<escribe el email del administrador>
      - AdminUser__Password=<escribe la contraseña del administrador>
      - Smtp__Host=<escribe el host del servidor smtp (smtp.example.com)>
      - Smtp__Port=<escribe el puerto de conexión al servidor smtp>
      - Smtp__Username=<escribe email de acceso a la cuenta>
      - Smtp__Password=<escribe la contraseña de acceso a la cuenta>
      - Smtp__From=<escribe la cuenta por defecto de envíos automáticos de emails>
      - Smtp__UseSsl=true
    command: ["dotnet", "TmbControl.WebAPI.dll", "--urls", "http://0.0.0.0:5000"]
    depends_on:
      - postgres-db
    logging:
        driver: json-file
        options:
          max-size: "10m"
          max-file: "5"
  
  frontend:
    image: nginx:stable-alpine
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-api
