using Microsoft.AspNetCore.Routing.Tree;
using TmbControl.Modules.Indicators.Entities;

namespace TmbControl.Modules.Indicators.Persistence;

public static class IndicatorsDbContextSeeder
{
    public static async Task SeedAsync(IndicatorsDbContext context)
    {


        if (!context.Frequencies.Any())
        {
            context.Frequencies.AddRange(
                new Frequency { Name = "Valor diario", Description = "Valor diario", Order = 1, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Frequency { Name = "Mes en curso", Description = "Valor del mes en curso", Order = 2, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Frequency { Name = "Valor semanal", Description = "Valor de la semana", Order = 3, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Frequency { Name = "Acumulado anual", Description = "Valor acumulado anual", Order = 4, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Frequency { Name = "Valor mensual", Description = "Valor mensual", Order = 5, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" }
            );
        }

        if (!context.Statuses.Any())
        {
            context.Statuses.AddRange(
                new Status { Name = "sin definir", CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Status { Name = "alerta", CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Status { Name = "peligro", CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Status { Name = "correcto", CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" }
                
            );
        }

        if (!context.Categories.Any())
        {
            context.Categories.AddRange(
                new Category { Name = "Generales", Description = "Indicadores generales", Order = 1, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Category { Name = "Pretatamiento", Description = "Indicadores de la etapa de pretatamiento", Order = 2, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Category { Name = "Biometanización", Description = "Indicadores de la etapa de biometanización", Order = 3, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Category { Name = "Generación eléctrica", Description = "Biometanización: generación eléctrica", Order = 4, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Category { Name = "Compostaje", Description = "Indicadores de la etapa de gestión de compostaje", Order = 5, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" },
                new Category { Name = "Tratamiento Agua y aire", Description = "Indicadores de agua y aire", Order = 6, CreatedAt = DateTime.UtcNow, CreatedBy = "Seeder" }

            );
        }

        await context.SaveChangesAsync();

        if (!context.Indicators.Any())
        {
            context.Indicators.AddRange(new List<Indicator>
            {
                #region Categoría 1 - Generales
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Entradas Fracción resto",
                    Code = "1.1",
                    Description = "",
                    Value = 250,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 1,
                    StatusId = 3,
                    Min = 0,
                    Max = 500,
                    Unit = "t",
                    XLocation = 15,
                    YLocation = 15,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Entradas FORS",
                    Code = "1.2",
                    Description = "",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 1,
                    StatusId = 3,
                    Min = 0,
                    Max = 100,
                    Unit = "t",
                    XLocation = 20,
                    YLocation = 20,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Tratamiento f. resto",
                    Code = "1.3",
                    Description = "",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 1,
                    StatusId = 3,
                    Min = 0,
                    Max = 100,
                    Unit = "t",
                    XLocation = 25,
                    YLocation = 25,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Tratamiento FORS",
                    Code = "1.4",
                    Description = "",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 1,
                    StatusId = 3,
                    Min = 0,
                    Max = 100,
                    Unit = "t",
                    XLocation = 30,
                    YLocation = 30,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Pérdida masa total",
                    Code = "1.5",
                    Description = "",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 1,
                    StatusId = 3,
                    Min = 16,
                    Max = 100,
                    Unit = "%",
                    XLocation = 35,
                    YLocation = 35,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 10,
                    IsAlertConfigured = true,
                    MinAlert = 11,
                    MaxAlert = 15,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Valorización",
                    Code = "1.6",
                    Description = "",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 1,
                    StatusId = 3,
                    Min = 47.5,
                    Max = 100,
                    Unit = "%",
                    XLocation = 40,
                    YLocation = 40,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 47.4,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                #endregion

                #region Categoría 2 - Pretatamiento             
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Rechazo Voluminoso",
                    Code = "2.1",
                    Description = "Sobre tratamiento",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 1,
                    Min = 0,
                    Max = 100,
                    Unit = "%",
                    XLocation = 45,
                    YLocation = 45,
                    IsErrorConfigured = true,
                    MinError = 20,
                    MaxError = 90,
                    IsAlertConfigured = true,
                    MinAlert = 30,
                    MaxAlert = 80,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Rechazo Fin línea",
                    Code = "2.2",
                    Description = "Sobre tratamiento",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 1,
                    Min = 0,
                    Max = 20,
                    Unit = "%",
                    XLocation = 50,
                    YLocation = 50,
                    IsErrorConfigured = true,
                    MinError = 26,
                    MaxError = 40,
                    IsAlertConfigured = true,
                    MinAlert = 21,
                    MaxAlert = 25,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Recuperación Cartón",
                    Code = "2.3",
                    Description = "Sobre tratamiento",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 1,
                    Min = 2.24,
                    Max = 5,
                    Unit = "%",
                    XLocation = 55,
                    YLocation = 55,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 1.9,
                    IsAlertConfigured = true,
                    MinAlert = 2,
                    MaxAlert = 2.23,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Recuperación Férrico",
                    Code = "2.4",
                    Description = "Sobre tratamiento",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 1,
                    Min = 1.29,
                    Max = 5,
                    Unit = "%",
                    XLocation = 60,
                    YLocation = 60,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 0.9,
                    IsAlertConfigured = true,
                    MinAlert = 1,
                    MaxAlert = 1.28,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Recuperación Aluminio",
                    Code = "2.5",
                    Description = "Sobre tratamiento",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 1,
                    Min = 0.28,
                    Max = 5,
                    Unit = "%",
                    XLocation = 65,
                    YLocation = 65,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 0.19,
                    IsAlertConfigured = true,
                    MinAlert = 0.2,
                    MaxAlert = 0.27,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Recuperación PET",
                    Code = "2.6",
                    Description = "Sobre tratamiento",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 3,
                    Min = 0.47,
                    Max = 5,
                    Unit = "%",
                    XLocation = 70,
                    YLocation = 70,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 0.36,
                    IsAlertConfigured = true,
                    MinAlert = 0.37,
                    MaxAlert = 0.46,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Recuperación PEAD",
                    Code = "2.7",
                    Description = "Sobre tratamiento",
                    Value = 50,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 3,
                    Min = 0.41,
                    Max = 5,
                    Unit = "%",
                    XLocation = 75,
                    YLocation = 75,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0.29,
                    IsAlertConfigured = true,
                    MinAlert = 0.3,
                    MaxAlert = 0.4,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Recuperación Brik",
                    Code = "2.8",
                    Description = "Sobre tratamiento",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 3,
                    Min = 0.24,
                    Max = 5,
                    Unit = "%",
                    XLocation = 65,
                    YLocation = 65,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 0.14,
                    IsAlertConfigured = true,
                    MinAlert = 0.15,
                    MaxAlert = 0.23,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Recuperación Vidrio",
                    Code = "2.9",
                    Description = "Sobre tratamiento",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 3,
                    Min = 0.59,
                    Max = 5,
                    Unit = "%",
                    XLocation = 67,
                    YLocation = 67,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 0.39,
                    IsAlertConfigured = true,
                    MinAlert = 0.4,
                    MaxAlert = 0.58,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Recuperación Madera",
                    Code = "2.10",
                    Description = "Sobre tratamiento",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 3,
                    Min = 0.24,
                    Max = 5,
                    Unit = "%",
                    XLocation = 70,
                    YLocation = 70,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 0.18,
                    IsAlertConfigured = true,
                    MinAlert = 0.19,
                    MaxAlert = 0.23,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Recuperación Subproductos",
                    Code = "2.11",
                    Description = "Sobre tratamiento",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 3,
                    Min = 5.75,
                    Max = 10,
                    Unit = "%",
                    XLocation = 72,
                    YLocation = 72,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 4.9,
                    IsAlertConfigured = true,
                    MinAlert = 5,
                    MaxAlert = 5.74,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                #endregion

                #region Categoría 3 - Biometanización
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Alimentación residuo, t/d eq.",
                    Code = "3.a.1",
                    Description = "Cantidad diaria de residuo alimentado al digestor",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 3,
                    StatusId = 3,
                    Min = 0,
                    Max = 0,
                    Unit = "t",
                    XLocation = 10,
                    YLocation = 10,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Ratio Nm3 gas/t eq.",
                    Code = "3.a.2",
                    Description = "Ratio de gas generado por tonelada equivalente",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 3,
                    StatusId = 3,
                    Min = 170,
                    Max = 250,
                    Unit = "Nm3/t",
                    XLocation = 20,
                    YLocation = 20,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 154,
                    IsAlertConfigured = true,
                    MinAlert = 155,
                    MaxAlert = 169,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Valorización como biogás, % s.trat.",
                    Code = "3.a.3",
                    Description = "Porcentaje valorizado como biogás respecto al total tratado",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 3,
                    StatusId = 3,
                    Min = 0,
                    Max = 0,
                    Unit = "%",
                    XLocation = 30,
                    YLocation = 30,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },

                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Tª interior digestor",
                    Code = "3.b.1",
                    Description = "Temperatura interna del digestor",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 1,
                    CategoryId = 3,
                    StatusId = 3,
                    Min = 46.6,
                    Max = 48,
                    Unit = "°C",
                    XLocation = 10,
                    YLocation = 10,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 44.9,
                    IsAlertConfigured = true,
                    MinAlert = 45,
                    MaxAlert = 46.5,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "SH2digestor",
                    Code = "3.b.2",
                    Description = "Nivel de sufhídrico en digestor",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 1,
                    CategoryId = 3,
                    StatusId = 3,
                    Min = 0,
                    Max = 250,
                    Unit = "kWh/Nm3",
                    XLocation = 20,
                    YLocation = 20,
                    IsErrorConfigured = true,
                    MinError = 501,
                    MaxError = 9999,
                    IsAlertConfigured = true,
                    MinAlert = 251,
                    MaxAlert = 500,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "pH digestor",
                    Code = "3.b.3",
                    Description = "Nivel de pH en el digestor",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 1,
                    CategoryId = 3,
                    StatusId = 3,
                    Min = 7.6,
                    Max = 8.5,
                    Unit = "kWh",
                    XLocation = 30,
                    YLocation = 30,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 6.9,
                    IsAlertConfigured = true,
                    MinAlert = 7,
                    MaxAlert = 7.5,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Nivel digestor",
                    Code = "3.b.4",
                    Description = "...",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 1,
                    CategoryId = 6,
                    StatusId = 3,
                    Min = 0,
                    Max = 0,
                    Unit = "kWh",
                    XLocation = 35,
                    YLocation = 36,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                #endregion

                #region Categoría 4 - Generación eléctrica
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "% gas quemado en antorcha",
                    Code = "3.c.1",
                    Description = "...",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 4,
                    StatusId = 2,
                    Min = 0,
                    Max = 2,
                    Unit = "%",
                    XLocation = 38,
                    YLocation = 38,
                    IsErrorConfigured = true,
                    MinError = 3.1,
                    MaxError = 10,
                    IsAlertConfigured = true,
                    MinAlert = 2.1,
                    MaxAlert = 3,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Ratio kWh/Nm3 en motor",
                    Code = "3.c.2",
                    Description = "...",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 4,
                    StatusId = 2,
                    Min = 1.85,
                    Max = 3,
                    Unit = "kWh",
                    XLocation = 40,
                    YLocation = 40,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 1.79,
                    IsAlertConfigured = true,
                    MinAlert = 1.8,
                    MaxAlert = 1.84,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "kWh/d generados motor",
                    Code = "3.c.3",
                    Description = "...",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 4,
                    StatusId = 2,
                    Min = 8200,
                    Max = 16000,
                    Unit = "kWh/d",
                    XLocation = 42,
                    YLocation = 42,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 8198,
                    IsAlertConfigured = true,
                    MinAlert = 8000,
                    MaxAlert = 8199,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "kWh/d generados FV",
                    Code = "3.c.4",
                    Description = "....",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 4,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "kWh",
                    XLocation = 50,
                    YLocation = 50,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Consumo planta, kWh/d",
                    Code = "3.c.5",
                    Description = "...",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 4,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "kWh",
                    XLocation = 60,
                    YLocation = 60,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Venta electricidad, kWh/d",
                    Code = "3.c.6",
                    Description = "Eficiencia de conversión del motor de gas a electricidad",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 4,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "kWh",
                    XLocation = 70,
                    YLocation = 70,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Rendimiento 118%",
                    Code = "3.c.7",
                    Description = "Rendimiento",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 4,
                    StatusId = 2,
                    Min = 118,
                    Max = 200,
                    Unit = "kWh",
                    XLocation = 70,
                    YLocation = 70,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 117,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                #endregion
            
                #region Categoría 5 - Compostaje
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Nº trincheras volteadas/d",
                    Code = "4.1",
                    Description = "Número de trincheras volteadas diariamente",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 1,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 20,
                    Max = 50,
                    Unit = "unidades",
                    XLocation = 10,
                    YLocation = 10,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 9,
                    IsAlertConfigured = true,
                    MinAlert = 10,
                    MaxAlert = 199,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "% uso patín",
                    Code = "4.2",
                    Description = "Porcentaje de uso del patín en compostaje",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 1,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "%",
                    XLocation = 20,
                    YLocation = 20,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "%H inicial maduración, f. resto",
                    Code = "4.3",
                    Description = "Porcentaje inicial de humedad en maduración, fracción resto",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "%",
                    XLocation = 30,
                    YLocation = 30,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Nº volteos en maduración, f. resto",
                    Code = "4.4",
                    Description = "Número de volteos realizados en maduración de fracción resto",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "volteos",
                    XLocation = 40,
                    YLocation = 40,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "%H entrada afino, f. resto",
                    Code = "4.5",
                    Description = "Porcentaje de humedad al entrar en afino, fracción resto",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "%",
                    XLocation = 50,
                    YLocation = 50,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "%H aire maduración",
                    Code = "4.6",
                    Description = "Humedad del aire en la etapa de maduración",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 1,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "%",
                    XLocation = 60,
                    YLocation = 60,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Dif Tª maduración-ext.",
                    Code = "4.7",
                    Description = "Diferencia de temperatura entre maduración y exterior",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 1,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "°C",
                    XLocation = 70,
                    YLocation = 70,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "[NH3] Maduración (mg/m3)",
                    Code = "4.8",
                    Description = "[NH3] Maduración (mg/m3)",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 1,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 25,
                    Max = 35,
                    Unit = "mg/m3",
                    XLocation = 70,
                    YLocation = 70,
                    IsErrorConfigured = true,
                    MinError = 41,
                    MaxError = 100,
                    IsAlertConfigured = true,
                    MinAlert = 36,
                    MaxAlert =40,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Relación Rech. Afino/MB",
                    Code = "4.9",
                    Description = "Relación entre rechazo de afino y materia bruta",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0.4,
                    Unit = "Afino/MB",
                    XLocation = 80,
                    YLocation = 80,
                    IsErrorConfigured = true,
                    MinError = 1,
                    MaxError = 2,
                    IsAlertConfigured = true,
                    MinAlert = 0.41,
                    MaxAlert = 0.9,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Producción compost FORS-A, % s./FORS-A recibida (año)",
                    Code = "4.10",
                    Description = "Tipo A",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 4,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "%",
                    XLocation = 90,
                    YLocation = 90,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Producción compost FORS-B, % s./FORS-B recibida (año)",
                    Code = "4.11",
                    Description = "Tipo B",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 4,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "%",
                    XLocation = 93,
                    YLocation = 93,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Producción enmiendas orgánicas, % s./trat.",
                    Code = "4.12",
                    Description = "Porcentaje de producción de enmiendas orgánicas sobre tratado",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 5,
                    StatusId = 2,
                    Min = 0,
                    Max = 0,
                    Unit = "%",
                    XLocation = 94,
                    YLocation = 94,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                #endregion

                #region Categoría 6 - Tratamiento Agua y Aire
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Gestión lixiviados, m3/d",
                    Code = "5.1",
                    Description = "Volumen diario gestionado de lixiviados",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 2,
                    StatusId = 1,
                    Min = 0,
                    Max = 0,
                    Unit = "m3",
                    XLocation = 20,
                    YLocation = 20,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Consumo agua",
                    Code = "5.2",
                    Description = "Consumo agua",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 2,
                    CategoryId = 6,
                    StatusId = 1,
                    Min = 0,
                    Max = 0,
                    Unit = "l",
                    XLocation = 30,
                    YLocation = 30,
                    IsErrorConfigured = false,
                    MinError = 0,
                    MaxError = 0,
                    IsAlertConfigured = false,
                    MinAlert = 0,
                    MaxAlert = 0,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Velocidad aire entrada B2",
                    Code = "5.3",
                    Description = "Velocidad del aire a la entrada del biofiltro B2",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 5,
                    CategoryId = 6,
                    StatusId = 1,
                    Min = 12,
                    Max = 15,
                    Unit = "m/s",
                    XLocation = 30,
                    YLocation = 30,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 9.9,
                    IsAlertConfigured = true,
                    MinAlert = 10,
                    MaxAlert = 11.9,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                },
                new ()
                {
                    Id = Guid.NewGuid(),
                    Name = "Caudal aire T3+T5 de B2",
                    Code = "5.4",
                    Description = "Caudal de aire combinado de T3 y T5 en biofiltro B2",
                    Value = 255,
                    Date = new DateOnly(2025, 03, 15),
                    FrequencyId = 5,
                    CategoryId = 6,
                    StatusId = 1,
                    Min = 70000,
                    Max = 100000,
                    Unit = "m3/h",
                    XLocation = 40,
                    YLocation = 40,
                    IsErrorConfigured = true,
                    MinError = 0,
                    MaxError = 64999,
                    IsAlertConfigured = true,
                    MinAlert = 65000,
                    MaxAlert = 69999,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = "Seeder"
                }
                #endregion
            });

        }

        // Crea el histórico simulado de cada indicador. Se generan 10 registros por cada indicador, con un intervalo de 1 día entre cada uno.
        if (!context.IndicatorHistories.Any())
        {
            foreach (var indicator in context.Indicators)
            {
                for (int i = 0; i < 10; i++)
                {
                    var history = new IndicatorHistory
                    {
                        Id = Guid.NewGuid(),
                        IndicatorId = indicator.Id,
                        Timestamp = DateTime.UtcNow.AddDays(-i),
                        Value = Random.Shared.NextDouble() * (indicator.Max - indicator.Min) + indicator.Min,
                        StatusId = Random.Shared.Next(1, 4)
                    };
                    context.IndicatorHistories.Add(history);
                }
            }
        }


        await context.SaveChangesAsync();
    }
}
