version: '3.8'

services:
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tmbcontrol
      POSTGRES_PASSWORD: <escribe la contraseña de la base de datos>
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mailhog:
    image: mailhog/mailhog
    restart: always
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI